name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Python and SQL files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 sqlfluff

      - name: Lint Python files with flake8
        run: |
          echo "Running flake8..."
          flake8 api dataloader etl \
            --count --select=E9,F63,F7,F82 --show-source --statistics
          echo "No python linting issue found."

      - name: Lint SQL files with sqlfluff
        run: |
          echo "Running sqlfluff..."
          sqlfluff lint etl
          echo "No SQL linting issue found."
